DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_message_room_status;
DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_message_offer;
DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_message;
DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_message_room;
DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_message_item_status;